### ISSUE TITLE
Windows Defender Treats it as Virus

### ISSUE THREAD

**Issue by MBCX** [kuvaus/LlamaGPTJ-chat#15]
Hello! I wanted to download the latest version of the programme. But when I do, Windows Defender detects it as trojan. This is kind of worrying since this did not happen before? Here's the picture of it blocking and removing it.
![Thread detected](https://github.com/kuvaus/LlamaGPTJ-chat/assets/63003002/6d6a2816-d871-4c1e-bd3f-ae3cfe828d6e)

Also, I noticed that you also remove all the older version downloads. May I ask why you did so?

**Comment by kuvaus** [comment]
Now this is alarming. :(

Thanks for pointing it out!! I will try to fix this asap.

The big changes in past couple versions was that I added ability to save the model state to disk. And then the ability to change the save_dir.

I think it could be because I added the --save_dir option to change the model save location because that was the latest change.  Let me undo the changes. I'd rather have a version that is not flagged than add those couple features.

Which version did you have before that did not alert the Defender?

> Also, I noticed that you also remove all the older version downloads. May I ask why you did so?

I always thought that it would be simpler to just have one version for everyone but now I realize there is much benefit to have all the old versions too. The [tags](https://github.com/kuvaus/LlamaGPTJ-chat/tags) still point to the source code of the old versions that you can download. I just need to rebuild the binaries.

**Comment by kuvaus** [comment]
Alright. First step:

I rebuild the binaries for all versions from v0.2.0 to v0.2.8. I just love Github actions for this! :)

See https://github.com/kuvaus/LlamaGPTJ-chat/releases

Could you please check that which version starts behaving badly with Defender. So I'll know how far I have to go back to remove features?

**Comment by MBCX** [comment]
Alright! I will try from 0.2.7 down to 0.2.0 and tell you if anything happens!

**Comment by MBCX** [comment]
OK, downloaded all versions from (newer) 2.8 to 2.5 (and tried them), **none of them where flagged**. I'm still wondering what caused it? You said it may have to do with the **--save_dir** flag, but I don't know. Something like that shouldn't trigger the antivirus considering that other terminal applications also have similar functionality.

**Comment by kuvaus** [comment]
Thank you!

I'm **super relieved** that it is no longer flagged.

It must be Windows Defender making a false positive. Looks like it did a very similar thing [here](https://github.com/facebookresearch/audiocraft/issues/44)

> OK, downloaded all versions from (newer) 2.8 to 2.5 (and tried them), **none of them where flagged**. I'm still wondering what caused it? You said it may have to do with the --save_dir flag, but I don't know. Something like that shouldn't trigger the antivirus considering that other terminal applications also have similar functionality.


It just was the only thing I could think of because as seen in the commit history, the commits [add save_dir](https://github.com/kuvaus/LlamaGPTJ-chat/commit/076c4575059c39973248632be02a960e28ddc759) and [Update README.md](https://github.com/kuvaus/LlamaGPTJ-chat/commit/91c800661da4707e45216291ef8246d6aea8371e) are literally the ONLY changes between v0.2.7 and v0.2.8. Just a few lines of code!

And you're right, this whole thing does not make any sense. Other programs can write files on user-specified folders too.

Sidenote:
I'll leave the old release versions there from now on. This was a good lesson. I wonder if I could somehow make github to automatically generate "md5sum" or something so that users could verify their files better.

**Comment by MBCX** [comment]
Well, since this has been resolved. I'm going to close the issue now. Many thanks for fixing the issue!
