### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by Sharik2468** [kuvaus/LlamaGPTJ-chat#21]
$ ./chat -m "E:/Program Files (x86)/ChatGPT/Models/ggml-vicuna-13b-1.1-q4_2.bin" -t 2
LlamaGPTJ-chat (v. 0.3.0)
LlamaGPTJ-chat: loading E:/Program Files (x86)/ChatGPT/Models/ggml-vicuna-13b-1.1-q4_2.bin
llama.cpp: loading model from E:/Program Files (x86)/ChatGPT/Models/ggml-vicuna-13b-1.1-q4_2.bin
Illegal instruction

What is this? Can you help me?

**Comment by kuvaus** [comment]
Hi,

Could you try the `chat-windows-latest-avx.exe` instead of `chat-windows-latest-avx2.exe` ?

I've had the illegal instruction error when a processor does not understand the avx2 instructions.

If the error still happens then I need to think about it more.

Oh and if you compiled it yourself, try adding the -DAVX2=OFF flag in the cmake:

```
mkdir build
cd build
cmake ..  -DAVX2=OFF
cmake --build . --parallel
```

**Comment by Sharik2468** [comment]
With chat-windows-latest-avx.exe no problem. This happens when I build. 
And yes, it helped. Thanks a lot!
